services:
  gateway-server:
    image: guilhermejr/sistema-gateway-server
    container_name: gateway-server
    restart: always
    ports:
      - "8080:8080"

networks:
  default:
    external: true
    name: rede