server:
  port: 8080

spring:
  application:
    name: gateway-server
  main:
    allow-bean-definition-overriding: true
  config:
    import: vault://
  cloud:
    vault:
      host: ${VAULT_HOST:localhost}
      port: ${VAULT_PORT:8200}
      scheme: ${VAULT_SCHEME:http}
      uri: ${VAULT_SCHEME:http}://${VAULT_HOST:localhost}:${VAULT_PORT:8200}
      token: ${VAULT_TOKEN:hvs.VSlxeCypMevB7HLAYZ1hB73L}
      generic:
        enabled: true
        application-name: gateway-server
    gateway:
      routes:
        - id: energia-service
          uri: lb://energia-service/
          predicates:
            - Path=/energia-service/**
          metadata:
            cors:
              allowedOrigins: ${frontend}
              allowedMethods: '*'
              allowedHeaders: '*'
              maxAge: 3600
        - id: autenticacao-service
          uri: lb://autenticacao-service/
          predicates:
            - Path=/autenticacao-service/**
          metadata:
            cors:
              allowedOrigins: ${frontend}
              allowedMethods: '*'
              allowedHeaders: '*'
              maxAge: 3600
        - id: supermercado-service
          uri: lb://supermercado-service/
          predicates:
            - Path=/supermercado-service/**
          metadata:
            cors:
              allowedOrigins: ${frontend}
              allowedMethods: '*'
              allowedHeaders: '*'
              maxAge: 3600
        - id: remedios-service
          uri: lb://remedios-service/
          predicates:
            - Path=/remedios-service/**
          metadata:
            cors:
              allowedOrigins: ${frontend}
              allowedMethods: '*'
              allowedHeaders: '*'
              maxAge: 3600
        - id: gastos-service
          uri: lb://gastos-service/
          predicates:
            - Path=/gastos-service/**
          metadata:
            cors:
              allowedOrigins: ${frontend}
              allowedMethods: '*'
              allowedHeaders: '*'
              maxAge: 3600
  boot:
    admin:
      client:
        url: ${monitoramentoHost}
        username: ${monitoramentoUser}
        password: ${monitoramentoPass}
        instance:
          metadata:
            user:
              name: ${actuatorUser}
              password: ${actuatorPass}

sistema:
  eureka:
    host: ${eurekaServerHost}
    login: ${eurekaServerUser}
    senha: ${eurekaServerPass}

eureka:
  client:
    serviceUrl:
      defaultZone: 'http://${sistema.eureka.login}:${sistema.eureka.senha}@${sistema.eureka.host}:8761/eureka'
  instance:
    hostname: ${eurekaHostname}

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: "*"
  info:
    env:
      enabled: true